# # This is a basic workflow to help you get started with Actions

# name: Main

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the develop branch
#   push:
#     branches: [ develop ]

#   pull_request:
#     types: [opened, reopened, synchronize]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:

#   annotate-pr:
#     runs-on: ubuntu-latest
#     name: Annotates pull request with metadata
#     steps:
#       - name: Annotate PR
#         uses: link-/PR-metadata-action@main
#         with:
#           owner: ${{ github.repository_owner }}
#           repo: ${{ github.event.repository.name }}
#           pr_number: ${{ github.event.number }}
#           token: ${{ secrets.GITHUB_TOKEN }}

#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       - name: Use Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14.x'

#       - name: Install dependencies
#         run: npm install

#       - name: Run test
#         run: npm test

#   deploy:
#     runs-on: ubuntu-latest

#     needs: [build]

#     steps:
#       - uses: actions/checkout@v2
#       - uses: akhileshns/heroku-deploy@v3.12.12
#         with:
#           heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#           heroku_app_name: "the-weather-backend" #Must be unique in Heroku
#           heroku_email: "1995talant@gmail.com"

name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
